### PR TITLE
WIP: A whole bunch of enhancements

### PR DESCRIPTION
**Pull request by mattiasgiese-giz**
First and foremost thank you very much for developing this module. It served me very well when i first tried to deploy Dokuwiki with Puppet. Along the way i implemented a set of enhancements needed for my particular use case. I am not sure whether you are interested in a merge, so i'll just leave this here as an PR for you to consider the changes and discuss them :-)

If you are interested i may as well split up the changes into different feature sets for easier merging.

### CODE REVIEW

**Comment by zyronix** [comment]
Good to hear that this module helped you. I haven't been working with Puppet anymore for some time, so my suggestion would be to hand over this project to you so you can enhance it further. If this sounds like a good solution for you, upload my original version of the module under your name to the forge. I'll than deprecate my module and point it to your module. After that you can further enhance the module.

**Comment by mattiasgiese-giz** [comment]
Heya,

i have uploaded the module here: https://forge.puppet.com/modules/fancyolaya/dokuwiki

Regards,

Mattias

**Comment by zyronix** [comment]
Hi Mattias,

For some reason I didn't get a notification for your comment, so sorry for the delayed comment. I have submitted a request to deprecated my module:
https://tickets.puppetlabs.com/browse/FORGE-583

In the mean time you can already start working on your own module and submit new versions. Once the deprecation has been completed my module will forward people towards your module.

Enjoy and thanks for taking over :).

Regards,
Romke

**Comment by mattiasgiese-giz** [comment]
> Enjoy and thanks for taking over :).

Thanks to you for letting me continue your work :-)

**Pull request closed without merging**
